### ISSUE TITLE
how to read the field using Python?

### ISSUE THREAD

**Issue by wentaozhu** [mattiaspaul/deedsBCV#4]
I want to read the displacement field by python. How to read the field using Python?

**Comment by junyuchen245** [comment]
> I want to read the displacement field by python. How to read the field using Python?

Hi, 

I came across your question recently, and I have a quick solution for it. You can add the following code to the end of `applyBCV.cpp` (just before `return 0`):
```
float* ddf=new float[sz*3];
for(int i=0;i<sz;i++){
	ddf[i]=ux[i]; ddf[i+sz]=vx[i]; ddf[i+sz*2]=wx[i];
}
gzWriteNifti("dense_disp.nii.gz",ddf,header,m,n,o,3);
```
This will save the displacement field to a nii.gz file (don't forget to compile the `.cpp` files again). You can then read the file in Python using the NiBabel package.

I noticed that it has been some time, but I hope this is still useful.

**Comment by wentaozhu** [comment]
Thank you!
