### ISSUE TITLE
Error: "terminate called after throwing an instance of 'std::bad_array_new_length'"

### ISSUE THREAD

**Issue by sunshichen** [mattiaspaul/deedsBCV#7]
Hi, I'm trying to do CT to MR image registration. But it throw an error when I was following the <a href="https://github.com/mattiaspaul/deedsBCV#4-run-deformable-deeds">"Step 4"</a> as:
![image](https://user-images.githubusercontent.com/23454839/120966566-fab42b00-c798-11eb-81c3-1e8a4fd074a9.png)

I have no idea the reason of this error. Could you help me with this?

**Comment by sunshichen** [comment]
Got the answer. It seems that the input images are too large.  After I downsampled inputs, the error disappeared.

**Comment by mattiaspaul** [comment]
Hi Sunshichen,

Did you find the answer?

Best wishes,

Mattias
